spring:
  application:
    name: super-assistant-app

  autoconfigure:
    exclude:
      - com.alibaba.cloud.ai.autoconfigure.dashscope.DashScopeMultimodalEmbeddingAutoConfiguration
      - com.alibaba.cloud.ai.autoconfigure.dashscope.DashScopeChatAutoConfiguration

  ai:
    dashscope:
      api-key: ${EMBEDDING_KEY}

    deepseek:
      api-key: ${DEEPSEEK_API_KEY}
      base-url: https://api.deepseek.com
      chat:
        options:
          model: deepseek-chat
          temperature: 0.7

    mcp:
      client:
        enabled: true
        name: super-assistant
        version: 1.0.0
        type: SYNC
    ##当启用工具回调时（默认行为），所有 MCP 客户端的已注册 MCP 工具都作为 ToolCallbackProvider 实例提供
        toolcallback:
          enabled: true
        sse:
          connections:
            email-server:
    ##将 Base URL 和 sse-endpoint 拼接起来，形成完整的访问地址：
              url: http://localhost:8081
              sse-endpoint: /sse

  datasource:
    url: jdbc:mysql://localhost:3306/superassistant
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 123456

mybatis-plus:
  configuration:
    map-underscore-to-camel-case: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  global-config:
    db-config:
      id-type: auto

server:
  port: 8080
