package com.itajay.superassistant.compact;

import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.databind.ObjectMapper;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;
import org.springframework.ai.chat.messages.Message;
import org.springframework.ai.chat.messages.SystemMessage;
import org.springframework.ai.chat.messages.UserMessage;

import java.io.IOException;
import java.nio.file.Files;
import java.nio.file.Path;
import java.time.Instant;
import java.util.ArrayList;
import java.util.Collections;
import java.util.List;

/**
 * Per-thread session memory for async compaction.
 *
 * Stores the summary generated by an async LLM compaction call alongside
 * the timestamp and the message count at the time of compaction.
 * On the next invocation, the hook injects the summary and discards
 * messages that were already summarized.
 *
 * File layout: {@code .compact/session_memory/{sanitized-threadId}.json}
 */
@JsonIgnoreProperties(ignoreUnknown = true)
public class SessionMemory {

    private static final Logger log = LoggerFactory.getLogger(SessionMemory.class);
    private static final ObjectMapper MAPPER = new ObjectMapper();

    private boolean pending;
    private String summary;
    private int preCompactMsgCount;
    private int preCompactTokens;
    private Instant compactTime;
    private List<String> recoveredFilePaths = Collections.emptyList();
    private String memoryProfile;
    private String planContent;

    public SessionMemory() {}

    // ── factory ──

    /** Create a pending entry when async compaction is fired. */
    public static SessionMemory createPending(int msgCount, int tokens) {
        SessionMemory sm = new SessionMemory();
        sm.pending = true;
        sm.preCompactMsgCount = msgCount;
        sm.preCompactTokens = tokens;
        sm.compactTime = Instant.now();
        return sm;
    }

    /** Mark as completed with the LLM summary and recovery data. */
    public void complete(String summary, List<String> recoveredFiles,
                         String memory, String plan) {
        this.pending = false;
        this.summary = summary;
        this.recoveredFilePaths = recoveredFiles != null ? recoveredFiles : Collections.emptyList();
        this.memoryProfile = memory;
        this.planContent = plan;
    }

    // ── IO ──

    public static SessionMemory load(String threadId) {
        Path file = resolveFile(threadId);
        if (!Files.exists(file)) return null;
        try {
            return MAPPER.readValue(file.toFile(), SessionMemory.class);
        } catch (IOException e) {
            log.warn("Failed to load session memory for thread={}: {}", threadId, e.getMessage());
            return null;
        }
    }

    public void save(String threadId) {
        Path file = resolveFile(threadId);
        try {
            Files.createDirectories(file.getParent());
            MAPPER.writerWithDefaultPrettyPrinter().writeValue(file.toFile(), this);
            log.debug("SessionMemory saved for thread={}: pending={}", threadId, pending);
        } catch (IOException e) {
            log.error("Failed to save session memory for thread={}", threadId, e);
        }
    }

    public static void delete(String threadId) {
        try {
            Files.deleteIfExists(resolveFile(threadId));
        } catch (IOException e) {
            log.warn("Failed to delete session memory for thread={}", threadId);
        }
    }

    // ── message construction ──

    /**
     * Build the messages to inject: boundary marker + summary + restored attachments.
     * Called when a completed summary is available.
     */
    public List<Message> buildInjectionMessages() {
        List<Message> result = new ArrayList<>();

        result.add(new SystemMessage(
                "[COMPACT BOUNDARY — context before this point summarized]\n"
                + "[Compacted at: " + compactTime + "]\n"
                + "[Pre-compaction: " + String.format("%,d", preCompactTokens) + " tokens across "
                + preCompactMsgCount + " messages]"
        ));

        result.add(new UserMessage(
                "[Context Compaction Summary — " + preCompactMsgCount
                + " earlier messages summarized]\n\n" + summary
        ));

        // Recovered files
        for (String path : recoveredFilePaths) {
            try {
                Path file = Path.of(path);
                if (Files.exists(file) && Files.isRegularFile(file)) {
                    String content = Files.readString(file);
                    int maxChars = CompactConfig.POST_COMPACT_MAX_TOKENS_PER_FILE * 2;
                    if (content.length() > maxChars) {
                        content = content.substring(0, maxChars) + "\n...[truncated]";
                    }
                    result.add(new SystemMessage(
                            "[Post-compact recovered: " + path + "]\n```\n" + content + "\n```"
                    ));
                }
            } catch (IOException ignored) {}
        }

        if (memoryProfile != null && !memoryProfile.isBlank()) {
            result.add(new SystemMessage(memoryProfile));
        }
        if (planContent != null && !planContent.isBlank()) {
            result.add(new SystemMessage(planContent));
        }

        return result;
    }

    // ── accessors ──

    public boolean isPending() { return pending; }
    public boolean hasSummary() { return !pending && summary != null && !summary.isBlank(); }
    public int getPreCompactMsgCount() { return preCompactMsgCount; }
    public int getPreCompactTokens() { return preCompactTokens; }
    public String getSummary() { return summary; }

    private static Path resolveFile(String threadId) {
        return CompactConfig.SESSION_MEMORY_DIR.resolve(sanitize(threadId) + ".json");
    }

    private static String sanitize(String s) {
        return s.replaceAll("[^a-zA-Z0-9._\\-]", "_");
    }
}
